# Generated by Django 3.2.23 on 2023-11-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AREA_INFO',
            fields=[
                ('AREA_CD', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AREA_NM', models.CharField(max_length=255)),
                ('AREA_CONGEST_LVL', models.CharField(max_length=100)),
                ('TEMP', models.FloatField()),
                ('PM10', models.FloatField()),
                ('PM25', models.FloatField()),
                ('CATEGORY', models.CharField(default='분류오류', max_length=50)),
            ],
        ),
    ]
