# Generated by Django 4.2.7 on 2023-11-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area_info",
            name="SKY_STTS",
            field=models.CharField(default="맑음", max_length=100),
        ),
    ]
