# Generated by Django 3.2.23 on 2023-11-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_area_info_sky_stts'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_info',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area_info',
            name='AREA_CD',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='area_info',
            name='SKY_STTS',
            field=models.CharField(default='정보없음', max_length=100),
        ),
    ]
