# Generated by Django 3.2.23 on 2023-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231107_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NICKNAME', models.CharField(max_length=30)),
                ('COMMENT_TEXT', models.CharField(max_length=400)),
                ('PUB_DATE', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='area_info',
            name='PM10',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='area_info',
            name='PM25',
            field=models.CharField(max_length=50),
        ),
    ]
