# Generated by Django 3.2.23 on 2023-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231107_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_info',
            name='IMAGE',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
