# Generated by Django 4.2.7 on 2023-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_area_info_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="area_info",
            name="CATEGORY",
            field=models.CharField(default="분류오류", max_length=50),
        ),
    ]
