# Generated by Django 4.2.7 on 2023-11-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_area_info_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="area_info",
            name="TIMESTAMP",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
