# Generated by Django 4.2.7 on 2023-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_area_info_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area_info",
            name="TEMP",
            field=models.CharField(max_length=50),
        ),
    ]
